-- Soporte para la campana de notificaciones.
-- Ejecutar con un usuario que pueda crear objetos en el esquema ICEBERG.

CREATE TABLE ICEBERG.NOTIFICACIONES (
    ID NUMBER(12) NOT NULL,
    NIT_DESTINATARIO VARCHAR2(30) NOT NULL,
    TIPO VARCHAR2(60) NOT NULL,
    MENSAJE VARCHAR2(1000) NOT NULL,
    ID_SOLICITUD NUMBER(12) NOT NULL,
    LEIDA NUMBER(1) DEFAULT 0 NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_LECTURA DATE,
    CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY (ID)
);

CREATE SEQUENCE ICEBERG.SEQ_NOTIFICACIONES
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER ICEBERG.TRG_NOTIFICACIONES_BI
BEFORE INSERT ON ICEBERG.NOTIFICACIONES
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT ICEBERG.SEQ_NOTIFICACIONES.NEXTVAL
        INTO :NEW.ID
        FROM DUAL;
    END IF;
END;
/

CREATE INDEX ICEBERG.IDX_NOTIF_DEST_LEIDA
    ON ICEBERG.NOTIFICACIONES (NIT_DESTINATARIO, LEIDA, FECHA_CREACION);

CREATE INDEX ICEBERG.IDX_NOTIF_SOLICITUD
    ON ICEBERG.NOTIFICACIONES (ID_SOLICITUD);
